### PR TITLE
Correct inBlock value for lists

### LINKED ISSUE #133: Incorrect inBlock value for lists during htmlToBlock
It seems that the inBlock value for lists is always set to null even they appear within an atomic block.

### PR DESCRIPTION
**Pull request by ddelrio1986**
Fixes #133.

### CODE REVIEW

**Comment by ddelrio1986** [comment]
Is there any chance to get this into a release? When within lists the value being returned is incorrect.

**Comment by ddelrio1986** [comment]
Is there any way to get anyone to take a look at this? The value is hard-coded to null when lists are actually in a block.

**Comment by benbriggs** [comment]
hi @ddelrio1986 so sorry for the huge delay. i had some time to take a quick look at this and wasn't able to get a test case working that this fixed with a nested list block - a simple `<p><ul><li>test</li></ul></p>` test input didn't work even with this change. can you add to this PR a test that fails currently and passes with this change? thank you for your patience!

**Comment by ddelrio1986** [comment]
@benbriggs I was trying to check the inBlock value for ul's and ol's and it seems to be hard-coded to null even though they really are inBlock. I'm not quite following what you're talking about in reference to things being split into its own block.

**Comment by benbriggs** [comment]
To clarify my example further:

```es6
const html = '<div>one<ul><li>two</li></ul></div>';
const contentState = convertFromHTML({
  htmlToBlock: (nodeName, node, lastList, inBlock) => {
    if (nodeName === 'div') {
      return 'test-block';
    }

    if (nodeName === 'li') {
      return {
        type: 'unordered-list-item',
        data: { inBlock },
      };
    }
  },
})(html);
```

Correct me if I'm wrong, your ideal scenario here would be a `ContentState` of shape:

```es6
[
  {
    type: 'test-block',
    text: 'one',
  },
  {
    type: 'unordered-list-item',
    text: 'two',
    data: {
      inBlock: 'test-block',
    },
  },
];
```

However, with your change the result is:
```es6
[
  {
    text: 'onetwo',
    type: 'test-block',
  },
];
```

So I think there's more work to be done for this to work as expected across the board. If this type of scenario isn't what you had in mind, can you provide an example input and expected output?

Thanks again!

**Pull request closed without merging**
