### PR TITLE
Emoji/Unicode support - fixes #12

### LINKED ISSUE #12: convertToHTML outputting unexpected character
Hey,

Nice job with this plugin, just trying it at the moment and seems to work nicely except for one small issue...

I've using the draft-js-plugins-emoji plugin and so have code to replace the emoji entities:

```
if (entity.type === 'emoji') {
  const unicode = escapeMap[entity.data.emojiUnicode];
  return `<img class="emoji" alt="${entity.data.emojiUnicode}" src="${EMOJI_BASE_URL}${unicode}.png" />`;
}
```

The raw state I'm putting in (I convert it from the JS object using convertFromRaw first) is:

```
{
   "entityMap":{
      "0":{
         "type":"emoji",
         "mutability":"IMMUTABLE",
         "data":{
            "emojiUnicode":"👍"
         }
      }
   },
   "blocks":[
      {
         "key":"69o72",
         "text":"👍 ",
         "type":"unstyled",
         "depth":0,
         "inlineStyleRanges":[

         ],
         "entityRanges":[
            {
               "offset":0,
               "length":1,
               "key":0
            }
         ],
         "data":{

         }
      }
   ]
}
```

The output I get is the expected img tag followed by a � character. Google informs me it is the "OBJECT REPLACEMENT CHARACTER".

I was just wondering if this is me misusing draft-convert or if something odd is going on during the conversion process?

### PR DESCRIPTION
**Pull request by tomkelsey**
Hi,

I think I worked out what was going on in #12 - emojis can count as two characters and so whenever you do string manipulation with an offset or by referencing the string as an array it can get rather confused!

A google suggested using ES6's spread operator to convert the string into an array sorts it out. This PR works for my purposes locally but I've only been converting to HTML (not from it) and haven't quite yet wrapped my head around how draftjs, let alone draft-convert, fully works.

It therefore might not be any good as is but hopefully its a good starting point if you want to fix the conversion of emojis :)

### CODE REVIEW

**Comment by tomkelsey** [comment]
I missed that you were using a combo of `substring` and `substr` so there was an index error in my use of `slice`.

Fixed now and it's passing all your tests :)

**Comment by benbriggs** [comment]
sorry for the delay - this looks more cleaner/more reliable to me, thanks! i suspect some similar changes may need to be made to convertFromHTML but I haven't experimented with adding emojis.

could you possibly add a test as well that this change causes to pass?

**Comment by tomkelsey** [comment]
A little later than expected but had a spare moment to catch up with your latest changes and add a test. 👍

**Comment by benbriggs** [comment]
thanks for catching this up! i'll try to find some time to see how this works with the `convertFromHTML` side of things but this should be strictly better than what we had before.

**Pull request merged**
