### PR TITLE
fix void elements in entityToHTML

### LINKED ISSUE #101: entityToHTML doesn't work for element like "img"
Assuming I have such an entityToHTML
```
      entityToHTML: (entity, originalText) => {
        if(entity.type === "IMAGE") {
          return (
             <img src={entity.data.src} style={{width: "100%"}}/>
          )
        }
      }
```

It goes to the https://github.com/HubSpot/draft-convert/blob/master/src/blockEntities.js#L34 to get tag element length:
```
      const entityHTML = getEntityHTML(entity, originalText);
      const converted = [...getElementHTML(entityHTML, originalText)
                        || originalText];

      const prefixLength = getElementTagLength(entityHTML, 'start');
      const suffixLength = getElementTagLength(entityHTML, 'end');

```

The getElementTagLength (https://github.com/HubSpot/draft-convert/blob/master/src/util/getElementTagLength.js#L6) use splitReactElement:
```
const getElementTagLength = (element, type = 'start') => {
  if (React.isValidElement(element)) {
    const length = splitReactElement(element)[type].length;

    const child = React.Children.toArray(element.props.children)[0];
    return length + (child && React.isValidElement(child)
      ? getElementTagLength(child, type)
      : 0
    );
  }
  ......
```

However the splitReactElement than treat the  as "void element" (https://github.com/HubSpot/draft-convert/blob/master/src/util/splitReactElement.js#L25) , where it directly returns a String, rather than `{start: <sth>, end: <sth>}`:
```
if (VOID_TAGS.indexOf(element.type) !== -1) {
    return ReactDOMServer.renderToStaticMarkup(element);
  }

```

Then the `splitReactElement(element)[type].length` report an error.

Isn't it an issue, or am I missing something?

### PR DESCRIPTION
**Pull request by benbriggs**
fixes #101 

I think this was an issue I ran into when trying to integrate flow, but it never made it to master. There were a couple places that didn't expect anything except a `{ start, end }` object from `splitReactElement`.

### CODE REVIEW

**Comment by Huvik** [comment]
I tried it on my project, but i got `Unknown DraftEntity key.`. https://i.imgur.com/c0UcyRJ.png

**Comment by Huvik** [comment]
Hey any news? :)

**Comment by benbriggs** [comment]
sorry for the long, long wait on this. @Huvik I don't think that error sounds related to this change since it's unrelated to fetching entities out of state. going to merge now!

**Comment by benbriggs** [comment]
landed in `draft-convert@2.0.2`

**Pull request merged**
