### PR TITLE
add support for encode whitespace

### PR DESCRIPTION
**Pull request by focus0802**
encode whtespace ` ` to `&nbsp;`

### CODE REVIEW

**Comment by benbriggs** [comment]
I'm not sure this makes sense as a part of draft-convert since it seems like it solves a pretty specific usecase. The encoding `&nbsp;` is for a different character from the normal space character so I'm don't think it belongs as standard behavior. I'd recommend adding a `.replace(' ', '&nbsp;')` to your code after running `convertToHTML`.

**Comment by focus0802** [comment]
I tried to use `replace` function.
original: `<p style="text-align: center;">some words</p>`
except: `<p style="text-align: center;">some&nbsp;words</p>`
actually: `<p&nbsp;style="text-align:&nbsp;center;">some&nbsp;words</p>`

**Comment by focus0802** [comment]
draft-js-export-html --- stateToHTML
```javascript
function encodeContent(text: string): string {
  return text
    .split('&').join('&amp;')
    .split('<').join('&lt;')
    .split('>').join('&gt;')
    .split('\xA0').join('&nbsp;')
    .split('\n').join(BREAK + '\n');
}

function encodeAttr(text: string): string {
  return text
    .split('&').join('&amp;')
    .split('<').join('&lt;')
    .split('>').join('&gt;')
    .split('"').join('&quot;');
}
```

**Comment by benbriggs** [comment]
Ah good point. Note that draft-js-export-html is replacing the character `\xA0` which is the other character I was referring to. I'd be happy to merge a change that makes that replacement, but that's not the same character being replaced here.

**Comment by focus0802** [comment]
got it, I will fix it to make it better!🙂

**Comment by focus0802** [comment]
I just tried replace `/xA0` or `&#xA0`, but it had no effect. I found that only replace ` ` is currently working, any other ideas?

**Comment by benbriggs** [comment]
I think this comes back to the original issue, which is that you're trying to replace regular spaces with non-breaking ones which are fundamentally different things. You'll need to input non-breaking spaces in your Draft editor or replace them within your contentState before using `convertToHTML`. I think something like this might work:

```
const nonBreakingContentState = ContentState.createFromBlockArray(
  contentState.getBlocksAsArray().map(block =>
    block.update('text', text => text.replace(' ', '\xA0'))
  )
);
```

**Pull request closed without merging**
